### ISSUE TITLE
JsonSerializationException: Self referencing loop detected for property 'Creator'

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#126]
`Self referencing loop detected for property 'Creator' with type 'JabbR_Core.Models.ChatUser'. Path 'A[0].OwnedRooms[0]'.`

Here is the stack trace

```
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.SignalR.Json.JsonSerializerExtensions.Serialize(JsonSerializer serializer, Object value, TextWriter writer)
   at Microsoft.AspNetCore.SignalR.Infrastructure.Connection.SerializeMessageValue(Object value)
   at Microsoft.AspNetCore.SignalR.Infrastructure.Connection.GetMessageBuffer(Object value)
   at Microsoft.AspNetCore.SignalR.Infrastructure.Connection.CreateMessage(String key, Object value)
   at Microsoft.AspNetCore.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNetCore.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNetCore.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNetCore.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , ChatUser )
   at JabbR_Core.Hubs.Chat.Join(Boolean reconnecting) in C:\Users\jaearle\Documents\Code\JabbR-Core\src\JabbR-Core\Hubs\Chat.cs:line 97
   at JabbR_Core.Hubs.Chat.Join() in C:\Users\jaearle\Documents\Code\JabbR-Core\src\JabbR-Core\Hubs\Chat.cs:line 78
   at Microsoft.AspNetCore.SignalR.Hubs.HubMethodDispatcher.<>c__DisplayClass10_0.<WrapVoidAction>b__0(IHub hub, Object[] parameters)
   at Microsoft.AspNetCore.SignalR.Hubs.HubDispatcher.Incoming(IHubIncomingInvokerContext context)
```

This is a result of refreshing the page, now that I've added `Clients.Caller.userNameChanged(user);`  in `Chat.cs` now. Adding this line solves the issue of `chat.state.name` being undefined in #113 and allows users to properly send messages (and ensures they're stored in the DB correctly), but when we refresh the page it calls `Join` again. Need a way to keep track of state between pages so we don't call this more than we have to (but `Chat.cs` is reinstantiated often with long polling so keeping track of that is going to be tough)

**Comment by adamtuliper** [comment]
Set to milestone to ensure we do this after fixing #129

**Comment by jcocchi** [comment]
This is happening when we pass in a full model instead of a view model to the client side. This specific example was fixed, but I have seen this same self referencing loop error in other places (presumably these will also be fixed by passing in a view model)
